/**
 * ContextLayer shared contract v1.
 *
 * This file is the single source of truth for communication between:
 * - the AI Backend;
 * - the Semantic DOM Engine;
 * - the Chrome Extension and public playground.
 *
 * Do not change fields or action names without lead-architect approval.
 * Keep every transport type JSON-serializable. Never place DOM nodes here.
 */

export const CONTRACT_VERSION = "1" as const;
export type ContractVersion = typeof CONTRACT_VERSION;

export type ElementKind =
  | "heading"
  | "paragraph"
  | "section"
  | "article"
  | "comment"
  | "card"
  | "list-item"
  | "table-row"
  | "link"
  | "other";

export interface ElementRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface SemanticElement {
  /** Snapshot-local identifier, for example `node-00015`. */
  id: string;
  kind: ElementKind;
  text: string;
  tagName: string;
  href?: string;
  attributes?: Record<string, string>;
  parentId?: string;
  visible: boolean;
  rect?: ElementRect;
}

export interface PageSnapshot {
  contractVersion: ContractVersion;
  /** Changes when the loaded document is replaced. */
  pageId: string;
  /** Increases after every meaningful re-index of the same document. */
  snapshotVersion: number;
  url: string;
  title: string;
  capturedAt: number;
  elements: SemanticElement[];
}

export type AgentActionType =
  | "SCROLL_TO"
  | "HIGHLIGHT"
  | "DIM"
  | "STRIKE"
  | "HIDE"
  | "RESTORE_ALL"
  | "CLEAR_EFFECT";

export type AgentAction =
  | {
      type: "RESTORE_ALL";
      targetElementIds?: never;
      explanation?: string;
    }
  | {
      type: Exclude<AgentActionType, "RESTORE_ALL">;
      targetElementIds: string[];
      explanation?: string;
    };

export interface AgentRequest {
  /** UUID generated by the client for tracing and duplicate protection. */
  requestId: string;
  query: string;
  page: PageSnapshot;
}

export interface AgentReference {
  elementId: string;
  excerpt?: string;
}

export interface AgentResponse {
  requestId: string;
  /** Must match the page in AgentRequest. */
  pageId: string;
  /** Must match the snapshot used to create this response. */
  snapshotVersion: number;
  message: string;
  references?: AgentReference[];
  actions: AgentAction[];
  limitations?: string[];
}

export type ActionFailureCode =
  | "UNKNOWN_ID"
  | "STALE_SNAPSHOT"
  | "DETACHED_NODE"
  | "UNSAFE_TARGET"
  | "UNSUPPORTED_ACTION"
  | "EXECUTION_FAILED";

export interface ActionFailure {
  elementId?: string;
  code: ActionFailureCode;
  message: string;
}

export interface ActionExecutionResult {
  type: AgentActionType;
  success: boolean;
  affectedElementIds: string[];
  failures: ActionFailure[];
}

/** Input passed by the extension integration layer to the DOM Engine. */
export interface ExecuteActionsRequest {
  pageId: string;
  snapshotVersion: number;
  actions: AgentAction[];
}

/**
 * Public interface implemented by the DOM Engine and consumed by the
 * extension/playground. Implementations keep live Element references private.
 */
export interface PageEngine {
  scan(): PageSnapshot;
  executeActions(request: ExecuteActionsRequest): ActionExecutionResult[];
}

export interface ApiError {
  code:
    | "INVALID_REQUEST"
    | "CONTEXT_TOO_LARGE"
    | "RATE_LIMITED"
    | "MODEL_ERROR"
    | "MODEL_TIMEOUT"
    | "INTERNAL_ERROR";
  message: string;
  requestId?: string;
}
